import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dev Resources",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <div className="p-5 sm:p-10 lg:px-[80px] lg:py-[32px] overflow-hidden">
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
